apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- digest: sha256:610a4786628389c56ad1ba1bdd834489e790067fb1d3f59e399e603da6d051c1
  name: controller
  newName: quay.io/prismacloud/pcc-operator
