# permissions for end users to edit consoles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: console-editor-role
rules:
- apiGroups:
  - pcc.paloaltonetworks.com
  resources:
  - consoles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pcc.paloaltonetworks.com
  resources:
  - consoles/status
  verbs:
  - get
