# permissions for end users to view consoledefenders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consoledefender-viewer-role
rules:
- apiGroups:
  - pcc.paloaltonetworks.com
  resources:
  - consoledefenders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pcc.paloaltonetworks.com
  resources:
  - consoledefenders/status
  verbs:
  - get
