apiVersion: pcc.paloaltonetworks.com/v1alpha1
kind: Defender
metadata:
  name: pcc-defender
  namespace: twistlock
spec:
  namespace: twistlock
  version: "21_04_439"
  defenderConfig:
    clusterAddress: twistlock-console.example.com
    consoleAddress: https://twistlock-console.example.com:8083
    docker: false
