---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: pcc-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: image-registry.openshift-image-registry.svc.cluster.local:5000/openshift-marketplace/pcc-operator-catalog:v0.2.0
  displayName: Prisma Cloud Compute Operator Catalog
  publisher: Palo Alto Networks
  updateStrategy:
    registryPoll:
      interval: 10m0s
