---
access_token: "{{ lookup('env', 'PCC_ACCESS_TOKEN') or credentials.accessToken }}"
license: "{{ lookup('env', 'PCC_LICENSE') or credentials.license }}"
password: "{{ lookup('env', 'PCC_PASSWORD') or credentials.password }}"
username: "{{ lookup('env', 'PCC_USERNAME') or credentials.username }}"

work_dir: /opt/ansible/twistlock
