apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: pcc-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/prismacloud/pcc-operator-catalog:v0.0.1
  displayName: Prisma Cloud Compute Operator Catalog
  publisher: Palo Alto Networks
  updateStrategy:
    registryPoll:
      interval: 10m0s
