---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: pcc-operator
  namespace: twistlock
spec:
  targetNamespaces:
  - twistlock
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: pcc-operator
  namespace: twistlock
spec:
  channel: stable
  name: pcc-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
